dannyhammer/toad

README.md, src/engine.rs, src/search.rs
resolves #7 
This also changes the default benchmark depth from 4 to 6, because a/b pruning is quite effective.
The code for running benchmarks will need to be changed soon, as computing a "prune rate" is not a useful metric (see bench results below).
Also updates `README.md` to include new changes, and adjusts some descriptions of commands.
SPRT results:
```
Elo   | 408.92 +- 46.70 (95%)
LLR   | 2.96 (-2.94, 2.94) [0.00, 3.00]
Games | N: 536 W: 467 L: 24 D: 45
Penta | [0, 0, 24, 45, 199]
```
Benchmark results:
```
+----- Benchmark Complete -----+
| time (ms)      : 1746        |
| nodes          : 19024419    |
| nps            : 10892548    |
| prune rate (%) : 99.86       |
+------------------------------+
```
bench: 19024419
=> feat: integrated alpha-beta pruning to search

README.md, src/engine.rs, src/eval.rs, src/search.rs
resolves #9 
---
Implements [MVV-LVA](https://www.chessprogramming.org/MVV-LVA) move ordering to be used in the search.
The current implementation of "move ordering" is using the [`Slice::sort_by_cached_key`](https://doc.rust-lang.org/std/primitive.slice.html#method.sort_by_cached_key) method and calling a `score_move` function. Right now, this function *only* scores moves by a MVV-LVA calculation. Further move ordering techniques (promotions, safe squares, etc.) will be considered later.
There were two major design decisions made during this PR:
A. Sorting the entire list with a built-in sort function
B. How MVV-LVA scores are calculated
Regarding A:
I initially read Rustic's [page on move ordering](https://rustic-chess.org/search/ordering/how.html) and wanted to implement that method. …
=> feat: added MVV-LVA move ordering

src/search.rs
resolves #8 
Much of this was already written when #22 was merged, because I was originally intending to do QSearch before MVV-LVA. However, when I ran benchmarks with QSearch before MVV-LVA, results were not great, so I switched the priority of those two.
Anyway, QSearch is now implemented using a fail soft framework, just like in Negamax. There is potentially room for speedup in `chessie` for generating captures only. Right now I am generating all legal moves and filtering out non-captures. It would be nice to generate *only* captures. However, that would require a special edge case whenever an en passant capture is available, so I'll just make an issue in `chessie` and leave this be for now.
SPRT:
---
```
Elo   | 100.50 +- 28.54 (95%)
LLR   | 2.96 …
```
=> feat: added quiescence search

Cargo.lock, Cargo.toml, src/cli.rs, src/engine.rs, src/search.rs
resolves #14 
Adds in draw detection for the following conditions:
- Insufficient material (courtesy of [this](https://github.com/dannyhammer/chessie/commit/083dee3dff8796dee36bdf4369b19810b2fa2b82) update in `chessie`)
- Draw by the 50-move rule
- 2-fold repetition detection
This one was messy (hence the 9 commits). To my knowledge (which may be incorrect), draws don't "add" much valuable data when running SPRT, and the player who causes the draw isn't penalized in any way. I hope to be incorrect about this, but I'm not sure how to discern if this is truly the case. Anyway, this led to confusing results when running SPRT. I would compare `dev` with `detect-draws` after adding in a check for 50-move detection, but the draw rate would still be astronomically high (the engines would draw …
=> feat: implemented draw detection

README.md, src/cli.rs, src/engine.rs, src/eval.rs, src/lib.rs, src/psqt.rs, src/score.rs, src/search.rs
resolves #35 
Adds piece-square tables to improve evaluation. PSQT values are copied from [PeSTO](https://www.chessprogramming.org/PeSTO%27s_Evaluation_Function#Source_Code), and are expected to be tuned later.
`Evaluator` has been modified to generate two evaluations (mid-game and end-game) simultaneously, and then lerp once at the end. Further investigation should be done to determine how best to lerp between mg/eg values, and how best to determine "endgame percentage."
---
SPRT (unreal gainer):
```
Elo   | 533.69 +- 96.63 (95%)
LLR   | 3.69 (-3.66, 3.66) [0.00, 5.00]
Games | N: 384 W: 360 L: 10 D: 14
Penta | [0, 1, 9, 13, 169]
```
https://pyronomy.pythonanywhere.com/test/22/
bench: 15602055
=> feat: added piece-square tables

Cargo.toml, README.md, src/cli.rs, src/engine.rs, src/main.rs, src/search.rs
resolves #31 
New:
- You can now pass UCI commands directly to the engine on startup without needing to use the `uci` prefix
- You can now pass multiple commands to the engine on startup with the `-c` flag
- Added a `--no-exit` flag to prevent engine from exiting after executing startup command(s)
- Help menus are a bit better
---
3k games:
```
Elo   | 2.43 +- 6.21 (95%)
Conf  | 8.0+0.08s Threads=1 Hash=16MB
Games | N: 3002 W: 1198 L: 1177 D: 627
Penta | [59, 115, 1145, 110, 72]
```
https://pyronomy.pythonanywhere.com/test/29/
* SPRT was not necessary, as this was a non-functional change
bench: 15602055
=> feat: added support for executing multiple commands on startup

src/search.rs
resolves #10 
Adds Principal Variation Search.
PVS by itself doesn't gain much, but we're also not *doing* anything in PV nodes yet. Knowing whether or not we're in a PV node is helpful for TT cutoffs, for example. So, for that reason, we're using a const generic `PV` into the search functions that tell us whether we're in a PV node.
---
SPRT:
```
Elo   | 9.81 +- 7.74 (95%)
LLR   | 2.95 (-2.94, 2.94) [0.00, 10.00]
Games | N: 4710 W: 1911 L: 1778 D: 1021
Penta | [257, 315, 1101, 402, 280]
```
https://pyronomy.pythonanywhere.com/test/31/
bench: 12944256
=> feat: added PVS

src/main.rs, src/search.rs
Refactors the code in `negamax` and `quiescence_search` to return `Score` values directly rather than returning a `Result<Score>`. If timeouts occur, the current `best` score is returned. If a timeout occurs, the `iterative_deepening` loop checks this and returns the result from the previous iteration.
---
Result of 4k games (no SPRT because non-functional change):
```
Elo   | 5.82 +- 6.72 (95%)
Conf  | 8.0+0.08s Threads=1 Hash=16MB
Games | N: 4116 W: 1625 L: 1556 D: 935
Penta | [142, 210, 1298, 253, 155]
```
https://pyronomy.pythonanywhere.com/test/40/
bench: 12944256
=> refactor: adjusted search code to not return `Result`

src/engine.rs, src/eval.rs, src/lib.rs, src/search.rs, src/ttable.rs, src/tune.rs, src/utils.rs
resolves #42 
The primary change here is the introduction of `tune.rs`, which contains macros that expand into values that will be tuned later. Right now, the only values present are for determining soft/hard timeouts in a search. More will be added over time, though, such as for aspiration windows. No tuning is being done presently, and likely won't be done until the engine is 3k+, so the format of these macros will likely change in the future.
Aside from that, there are several small refactors, such as function/variable name changes, some extra comments, etc.
---
SPRT:
```
Elo   | 4.03 +- 4.56 (95%)
LLR   | 3.00 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 7750 W: 3128 L: 3038 D: 1584
Penta | [234, 333, 2684, 357, 267]
``` …
=> refactor: refactored code to not use magic numbers

src/search.rs, src/tune.rs
resolves #17 
This PR implements Aspiration Windows into the search. Values for the initial aspiration window size and minimum depth at which to apply aspiration windows have been added to `tune.rs` for tuning later. Current impl starts at depth 2 with a window of 1/4 Pawn, then widens exponentially on each failure.
Big thanks to @Ciekce on the EP discord for providing me with [some](https://chess.swehosting.se/test/6205/) [references](https://chess.swehosting.se/test/6206/) for Elo gains, answering lots of my questions, and explaining some of the Stormphrax source code.
---
SPRT:
```
Elo   | 58.24 +- 24.61 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 10.00]
Games | N: 572 W: 278 L: 183 D: 111
Penta | [21, 39, 113, 50, 63]
``` …
=> feat: added Aspiration Windows with gradual widening

README.md, src/search.rs, src/tune.rs
Aspiration Windows now change in size depending on the depth at which they were calculated. The idea here is that we are more likely to have a stable search at higher depths, so our AW can be narrower.
---
SPRT:
```
Elo   | 1.82 +- 4.96 (95%)
LLR   | -2.96 (-2.94, 2.94) [0.00, 10.00]
Games | N: 12802 W: 5208 L: 5141 D: 2453
Penta | [846, 904, 2864, 911, 876]
```
https://pyronomy.pythonanywhere.com/test/60/
bench: 13225972
=> feat: tweaked Aspiration Windows to change size based on depth

.github/workflows/compile-and-release.yml, .github/workflows/release-please.yml
resolves #1 
Adds a release pipeline based on [this example](https://github.com/dannyhammer/rust-release-pipeline) to automatically compile binaries for Windows, MacOS, and Linux.
bench: 13225972
=> feat: added release pipeline through GitHub Actions

Makefile, README.md
resolves #46 
Adds in a PowerShell script equivalent to the `sed` script to fetch the name and version from `Cargo.toml` when compiling. Only executes if running `make` on Windows.
---
bench: 13225972
=> fix: fixed bug causing `make` to fail when `sed` not present on Windows

src/engine.rs, src/score.rs, src/search.rs
refactor: moved node counter after recursive call
refactor: hash tables are cleared after each bench
refactor: cleaned up const generics a bit
---
SPRT:
```
Elo   | 0.60 +- 6.72 (95%)
LLR   | 3.04 (-2.94, 2.94) [-10.00, 0.00]
Games | N: 6368 W: 2586 L: 2575 D: 1207
Penta | [381, 442, 1530, 447, 384]
```
https://pyronomy.pythonanywhere.com/test/118/
bench: 14087451
=> refactor: misc refactors

src/tune.rs
Honestly? I'm not entirely sure why this made a difference at all. Let alone a positive difference.
I suspect this difference will go away with #28, #68 or other features that affect move ordering.
---
SPRT:
```
Elo   | 12.65 +- 9.54 (95%)
LLR   | 3.00 (-2.94, 2.94) [0.00, 10.00]
Games | N: 3600 W: 1497 L: 1366 D: 737
Penta | [226, 255, 752, 296, 271]
```
https://pyronomy.pythonanywhere.com/test/127/
bench: 11371856
=> fix: set `Score::BASE_MOVE_SCORE` to `0` (from `-32768`)

Cargo.toml, README.md, src/board/moves.rs, src/board/perft.rs, src/board/position.rs, src/cli.rs, src/engine.rs, src/main.rs, src/search.rs, src/ttable.rs, src/utils.rs, tests/perft.rs
Refactors the engine and game's code to better support playing multiple variants of chess. No functional changes beyond the addition of the `changevariant` command, which may be removed at a later date.
As different variants have different rules (Chess960 has different castling notation, Horde has no King, etc.), I wanted way to cleanly have different variants abide by these different rules while also minimizing code duplication. My decision wast to have a marker trait called `Variant` on the `Game` struct, stored in a `PhantomData` as to not take up space. This marker trait has variant-specific functions such as formatting castling rights and displaying moves (right now, it only has functions that are different in standard vs chess960).
That was a simple change. The tricky part was …
=> refactor: add better support for playing different chess variants

README.md, src/board/position.rs, src/engine.rs, src/main.rs, src/search.rs, src/tune.rs
resolves #26 
Implements null move pruning in `negamax` under the following restrictions:
- Must not be in a PV node
- Must not be in check
- Depth must be at least `MIN_NMP_DEPTH` (3)
- Cannot make two null moves in a row
- Board state cannot consist solely of Kings and Pawns
This was a large gainer, and didn't need much tweaking.
Here is the SPRT for avoiding NMP when in PV nodes:
```
Elo   | 6.63 +- 5.12 (95%)
LLR   | 3.11 (-2.94, 2.94) [0.00, 10.00]
Games | N: 10854 W: 4056 L: 3849 D: 2949
Penta | [544, 974, 2265, 1019, 625]
```
https://pyronomy.pythonanywhere.com/test/140/
---
SPRT:
```
Elo   | 156.17 +- 41.15 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 10.00]
Games | N: 242 W: 152 L: 50 D: 40
Penta | [2, 7, 43, …
```
=> feat: null move pruning

README.md, src/score.rs, src/search.rs, src/tune.rs
resolves #25 
Implements Reverse Futility Pruning within the `negamax` search. The values for `RFP_MARGIN` and `MAX_RFP_DEPTH` can be accredited to @Ciekce, author of [Stormphrax](https://github.com/Ciekce/Stormphrax), from [this Discord discussion](https://discord.com/channels/719576389245993010/719576389690589244/1307412495140651159).
---
SPRT:
```
Elo   | 72.27 +- 26.91 (95%)
LLR   | 2.95 (-2.94, 2.94) [0.00, 10.00]
Games | N: 434 W: 203 L: 114 D: 117
Penta | [9, 35, 73, 58, 42]
```
https://pyronomy.pythonanywhere.com/test/145/
bench: 20141032
=> feat: reverse futility pruning

CHANGELOG.md
I messed up the release pipeline somehow and it's trying to release 1.4.0 again. Let's fix that.
bench: 20183015
=> fix: fixed CHANGELOG and auto-release pipeline

toad/src/score.rs, toad/src/search.rs, toad/src/ttable.rs
- Removes mate distance correction from TT tables.
- Replaces all mate distance stuff with one simple `if` statement.
- Makes mate distance pruning unnecessary.
=> accurate mate scores

src/search.rs
It was pointed out to me that I was skipping draw detection at ply 1, so this PR fixes that.
---
SPRT:
```
Elo   | -1.02 +- 1.67 (95%)
LLR   | 2.90 (-2.25, 2.89) [-5.00, 0.00]
Games | N: 72870 W: 21759 L: 21972 D: 29139
Penta | [2019, 7934, 16714, 7777, 1991]
```
https://pyronomy.pythonanywhere.com/test/789/
(note: it's for a different branch, but the contents of that branch and this one are equal- minus the annoying merge conflicts)
bench: 8515103
=> fix: removed draw detection at ply 1
